# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  publish = "dist"

[[redirects]]
  from = "/login"
  to = "/"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/"
  status = 200

[[redirects]]
  from = "/editProfile"
  to = "/"
  status = 200

[[redirects]]
  from = "/changePassword"
  to = "/"
  status = 200

[[redirects]]
  from = "/404"
  to = "/"
  status = 200

[[redirects]]
  from = "/serverError"
  to = "/"
  status = 200

